### ISSUE TITLE
update please

### ISSUE THREAD

**Issue by malikshi** [cbeuw/Cloak-android#1]
its work for pc version but not working properly with android apps, even waiting for couple minutes.  please adjust so compatible with new shadowsocks apps

**Comment by jeffshead** [comment]
Try turning off **IPv6 Route**. It works for me on all apps except for a clock sync app for rooted Android phones. Other than that, all of my apps use the proxy without issue; including banking apps.

**Comment by malikshi** [comment]
> Try turning off **IPv6 Route**. 
its work, i mean if one uid used by many user at same time somehow its got slow, would u like to share config for new user uid? speed, tranfer rate and etc? usually im share it one main uid for my user

**Comment by jeffshead** [comment]
I have only one single user at a time in my setup. I have not tested with multiple users. With one user, speed and transfer rate is the same as direct connection for me. Very fast.

**Comment by malikshi** [comment]
yea i know if one single user, but if many user using it same time even server would stop need to restart service, even im try use monit to solve this in case server not respond

**Comment by jeffshead** [comment]
Does your server have enough entropy?

**Comment by malikshi** [comment]
> Does your server have enough entropy?

i think im installing haveged in my server,
> root@ssh:~# cat /proc/sys/kernel/random/entropy_avail
> 4013

**Comment by jeffshead** [comment]
That's more entropy than I have. I don't know what else to suggest. Hopefully, the author will respond.

**Comment by cbeuw** [comment]
> if one uid used by many user at same time somehow its got slow

I'll investigate into this. Thanks for the feedback!

**Comment by malikshi** [comment]
@cbeuw can u help me, for every user has 40Mbps up/down in their internet speed so how to setup new UID with expired 7 days,
Enter the the newly generated UID, enter SessionsCap (maximum amount of concurrent sessions a user can have), UpRate and DownRate (in bytes/s), UpCredit and DownCredit (in bytes) and ExpiryTime (as a unix epoch)
I don't understand it

**Comment by windstander** [comment]
Untick the UDP DNS in shadowsocks android.
