### ISSUE TITLE
Screenshots for F-Droid

### ISSUE THREAD

**Issue by mondlicht-und-sterne** [cbeuw/Cloak-android#19]
You can add Screenshots for F-Droid, too, if you want.
https://f-droid.org/en/docs/All_About_Descriptions_Graphics_and_Screenshots/
https://gitlab.com/snippets/1895688
That was simply information about what is still possible. You would then only have to enter the
screenshots in fastlane. This is just one way that you can also add screenshots to the app view
if you can. If you added screenshots (then F-Droid is happy) and if you can't add any -> then
you can close the issue because it was only an info. Thank you that your app is available in
fdroid. Very much for your attention.

**Comment by rhclayto** [comment]
I don't find this in F-Droid.

**Comment by mondlicht-und-sterne** [comment]
@rhclayto https://apt.izzysoft.de/fdroid/index/apk/com.github.shadowsocks.plugin.ck_client

**Comment by Korb** [comment]
Still no screenshots at https://f-droid.org/packages/com.github.shadowsocks.plugin.ck_client/

![Screenshot_2023_1226_005107_org fdroid fdroid](https://github.com/cbeuw/Cloak-android/assets/3509797/7cb6f749-5260-4db0-a62b-74be3b5a49a2)
