### ISSUE TITLE
v2.5.5 Open Failed: ENOENT (No such file or directory)

### ISSUE THREAD

**Issue by windstander** [cbeuw/Cloak-android#22]
v2.5.5 can not work on Mi 11 MIUI 12.5

**Comment by cbeuw** [comment]
Should be fixed with https://github.com/cbeuw/Cloak-android/pull/23. Try the v2.5.5-fix release?

**Comment by windstander** [comment]
> 
> 
> Should be fixed with #23. Try the v2.5.5-fix release?

Yes, it works.
