### ISSUE TITLE
2.6.0 but download link is 2.5.5 apk?

### ISSUE THREAD

**Issue by windstander** [cbeuw/Cloak-android#24]
Providing the wrong file?

**Comment by IzzySoft** [comment]
My updater also complains the file at tag 2.6.0 identifies as v2.5.5 – and tries to re-download it daily. Looks like you forgot to update `versionCode` and `versionName` in [`build.gradle`](https://github.com/cbeuw/Cloak-android/blob/master/app/build.gradle):

```gradle
        versionCode 17
        versionName '2.5.5'
```

Could you please fix that and attach a new APK, @cbeuw? Thanks in advance!

**Comment by windstander** [comment]
@cbeuw You latest release is still 2.5.5.

**Comment by windstander** [comment]
https://github.com/cbeuw/Cloak-android/releases/tag/v2.6.0-fix
@cbeuw

**Comment by IzzySoft** [comment]
Thanks!
