### ISSUE TITLE
license question

### ISSUE THREAD

**Issue by IzzySoft** [cbeuw/Cloak-android#26]
Can you please state what license this app is covered by? I could find no information in the repo here.

**Comment by IzzySoft** [comment]
@cbeuw any note?

**Comment by cbeuw** [comment]
Oops sorry I neglected this. GPLv3 or later is now added, same as shadowsocks-android since this uses code snippets copied from that repo

**Comment by IzzySoft** [comment]
Great, thanks Andy! So I had [guessed correctly](https://apt.izzysoft.de/fdroid/index/apk/com.github.shadowsocks.plugin.ck_client) at least :smile: And yeah, things happen – and one misses notifications. Good this "missing" didn't continue :rofl:

**Comment by linsui** [comment]
Since the license is added, would you like to publish the app to the main F-Droid repo?
