### ISSUE TITLE
RemoteHost option is not available in client config for Transport = direct

### ISSUE THREAD

**Issue by selivan** [cbeuw/Cloak-android#35]
It is necessary if Transport mode is direct.

**Comment by selivan** [comment]
fix: https://github.com/cbeuw/Cloak-android/pull/36

**Comment by cbeuw** [comment]
Huh, `RemoteHost` shouldn't be required in Cloak's config since it obtains the address from Shadowsocks

**Comment by selivan** [comment]
My mistake, it really does so.
