### ISSUE TITLE
Where should we put the RemoteHost in android plugin?

### ISSUE THREAD

**Issue by pouyaesm** [cbeuw/Cloak-android#39]
In desktop version I set 127.0.0.1:1984 for shadowsocks and put the remote host in ckclient.json next to cloak executable.
But when I load the cloak plugin in shadowsocks there is no place for RemoteHost in Configuration section.

**Comment by cbeuw** [comment]
You do not need to set RemoteHost explicitly on Android as it's operating as a Shadowsocks plugin. The server setting in Shadowsocks is used directly by Cloak.

**Comment by pouyaesm** [comment]
> You do not need to set RemoteHost explicitly on Android as it's operating as a Shadowsocks plugin. The server setting in Shadowsocks is used directly by Cloak.

Thanks, I managed to make it work by using 443 for Remote Port instead of 1984 or the shadowsocks server port.

**Comment by DNA-h** [comment]
@pouyaesm Can I get further information on this matter from you?
