### ISSUE TITLE
Remote DNS not properly forwarded

### ISSUE THREAD

**Issue by georgh-** [cbeuw/Cloak-android#4]
I can successfully establish connections between my Android phone and my server using the Cloak plugin. I see active connections on the server and applications work.

However, if I enable remote DNS resolution, then it stops working (DNS resolution, it looks like traffic is still forwarded to IPs). I haven't tried any other plugins, so not sure if this could be related to shadowsocks app instead of cloak plugin.

I have tried to get more detailed logs using adb-logcat without success.

I also have checked the ck-server logs, nothing special is logged.

No problems when using ss-client from a laptop.

ss-server shadowsocks-libev 3.1.3
ck-server 1.1.1
android shadowsocks from Google play 4.7.4
cloak plugin apk downloaded from github 1.0.0
Phone Oneplus 6
Android version 9
Oxygen OS beta 21

**Comment by cbeuw** [comment]
Do you mean `Send DNS over UDP`? Cloak doesn't support UDP so this feature can't be used

**Comment by georgh-** [comment]
Understood, thanks for your response!

**Comment by georgh-** [comment]
I realized that the Russian translation of Shadowsocks uses "DNS redirection" instead of three correct text "Send DNS over UDP".

Therefore I was mistaken thinking that this setting had to be enabled to have remote DNS.

**Comment by georgh-** [comment]
Reported to Shadowsocks upstream:
https://github.com/shadowsocks/shadowsocks-android/issues/2251

**Comment by georgh-** [comment]
Reported to Shadowsocks upstream:
https://github.com/shadowsocks/shadowsocks-android/issues/2251
